server:
  port: 8080
  servlet:
    context-path: /BootIntercepter  #配置ContextPath

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_demo?serverTimezone=UTC&useAffectedRows=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 0 # Redis数据库索引（默认为0）
    jedis:
      pool:
        max-active: 8 # 最大活跃连接数
        max-wait: -1  # 获取连接时的最大等待毫秒数(-1阻塞不确定的时间)
        max-idle: 500 # 最大空闲连接数
        min-idle: 0 # 最小空闲连接数
    timeout: 1000 # 连接超时时间（毫秒）
  thymeleaf:
    cache: false  #开发时关闭缓存,不然没法看到实时页面
    encoding: utf-8
    servlet:
      content-type: text/html

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.test1.entity

logging:
  level:
    com.test1.dao: DEBUG
    org.springframework: INFO
